version: '3.8'

services:
  front:
    container_name: front
    build:
      context: ./front
    ports:
      - 8081:80
    depends_on:
      back:
        condition: service_healthy

  back:
    container_name: back
    build:
      context: ./back
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./build/libs/my-blog.jar:/app/my-blog.jar
    command: java -jar /app/my-blog.jar
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  db:
    image: postgres:13.3
    container_name: db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myblogdb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: