version: '3.8'

services:
  tomcat:
    image: 'bitnami/tomcat:latest'
    container_name: tomcat
    ports:
      - 8080:8080
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./target/my-blog.war:/opt/bitnami/tomcat/webapps/my-blog.war
  db:
    image: postgres:13.3
    container_name: db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myblogdb
    volumes:
      - db-data:/val/lib/postgresql/data

volumes:
  db-data: