version: '3.8'

services:
  app:
    image: openjdk:21-jdk-slim
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./target/my-blog.jar:/app/my-blog.jar
    command: java -jar /app/my-blog.jar
  db:
    image: postgres:13.3
    container_name: db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myblogdb
    volumes:
      - db-data:/val/lib/postgresql/data

volumes:
  db-data: